using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;

namespace ServiceClients.Kraken.Model
{
    /// <summary>
    /// Holds resize settings parameters. Has a new GUID Id automatically generated.
    /// </summary>
    public class Resize
    {
        /// <summary>
        /// Gets or sets the identifier. Has a new value generated by default.
        /// </summary>
        /// <value>The identifier.</value>
        [JsonProperty("id")]
        public Guid Id { get; set; } = Guid.NewGuid();

        /// <summary>
        /// Gets or sets the width.
        /// </summary>
        /// <value>The width.</value>
        [JsonProperty("width")]
        public int? Width { get; set; }

        /// <summary>
        /// Gets or sets the height.
        /// </summary>
        /// <value>The height.</value>
        [JsonProperty("height")]
        public int? Height { get; set; }

        /// <summary>
        /// Gets or sets the strategy.
        /// </summary>
        /// <value>The strategy.</value>
        [JsonProperty("strategy")]
        [JsonConverter(typeof(StringEnumConverter))]
        public Strategy Strategy { get; set; }

        /// <summary>
        /// Gets or sets the color of the background.
        /// </summary>
        /// <value>The color of the background.</value>
        [JsonProperty("background")]
        public string BackgroundColor { get; set; }

        /// <summary>
        /// Gets or sets the size.
        /// </summary>
        /// <value>The size.</value>
        [JsonProperty("size")]
        public int? Size { get; set; }

        /// <summary>
        /// Gets or sets the crop mode.
        /// </summary>
        /// <value>The crop mode.</value>
        [JsonProperty("crop_mode")]
        public string CropMode { get; set; }

        /// <summary>
        /// Gets or sets the storage path.
        /// </summary>
        /// <value>The storage path.</value>
        [JsonProperty("storage_path")]
        public string StoragePath { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the image should be enhanced.
        /// </summary>
        /// <value><c>true</c> if enhanced; otherwise, <c>false</c>.</value>
        [JsonProperty("enhance")]
        public bool Enhance { get; set; }
    }
}